---
  name: Audit
  
  on:
    workflow_call:
  
  jobs:
    audit:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          go-version: [ '1.21' ]
      steps:
        - name: Checkout
          uses: actions/checkout@v3
  
        - name: Setup Go
          uses: actions/setup-go@v4
          with:
            go-version: ${{ matrix.go-version }}

        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.10'

        - name: Install python package
          run: pip3 install shamir-mnemonic && shamir create 2of3

        - name: Verify dependencies
          run: go mod verify
  
        - name: Build
          run: go build -v ./...
  
        - name: Run gofmt
          run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
  
        - name: Run go vet
          run: go vet ./...
  
        - name: Install staticcheck
          run: go install honnef.co/go/tools/cmd/staticcheck@latest
  
        - name: Run staticcheck
          env:
            LINT: "//lint:file-ignore SA1019 Ignore all deprecation errors, it's generated"
          run: staticcheck ./...
  
        - name: Install golangci-lint
          run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
  
        - name: Run golangci-lint
          run: golangci-lint run --timeout 5m
  
        - name: Run tests
          run: go test -race -vet=off ./...