---
name: Audit

on: [push]

jobs:
  audit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.21' ]
        directory: [ './', 'client' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Checkout dependency
        uses: actions/checkout@v4
        with:
          repository: rddl-network/bc-slip39-go
          path: bc-slip39-go

      - name: Build dependency
        run: |
          pushd bc-slip39-go
          ./deps.sh
          popd

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Verify dependencies
        working-directory: ${{ matrix.directory }}
        run: go mod verify

      - name: Build
        working-directory: ${{ matrix.directory }}
        run: go build -v ./...

      - name: Run gofmt
        working-directory: ${{ matrix.directory }}
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi

      - name: Run go vet
        working-directory: ${{ matrix.directory }}
        run: go vet ./...

      - name: Install staticcheck
        working-directory: ${{ matrix.directory }}
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        env:
          LINT: "//lint:file-ignore SA1019 Ignore all deprecation errors, it's generated"
        working-directory: ${{ matrix.directory }}
        run: staticcheck ./...

      - name: Install golangci-lint
        working-directory: ${{ matrix.directory }}
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run golangci-lint
        working-directory: ${{ matrix.directory }}
        run: golangci-lint run --timeout 5m

      - name: Run tests
        run: |
          go run cmd/shamir-coordinator/main.go
          pushd ${{ matrix.directory }}
          go test -race -vet=off ./...
