---
  name: Audit
  
  on: [push]

  
  jobs:
    audit:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          go-version: [ '1.21' ]
          directory: [ './', 'client' ]
      steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            submodules: true
  
        - name: Setup Go
          uses: actions/setup-go@v4
          with:
            go-version: ${{ matrix.go-version }}

        - name: Install dependencies
          run: |
            pushd bc-slip39-go
            ./deps.sh
            popd

        - name: Verify dependencies
          run: |
            pushd ${{ matrix.directory }}
            go mod verify
  
        - name: Build
          run: |
            pushd ${{ matrix.directory }}
            go build -v ./...
  
        - name: Run gofmt
          run: |
            pushd ${{ matrix.directory }}
            if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
  
        - name: Run go vet
          run: |
            pushd ${{ matrix.directory }}
            go vet ./...
  
        - name: Install staticcheck
          run: go install honnef.co/go/tools/cmd/staticcheck@latest
  
        - name: Run staticcheck
          env:
            LINT: "//lint:file-ignore SA1019 Ignore all deprecation errors, it's generated"
          run: |
            pushd ${{ matrix.directory }}
            staticcheck ./...
  
        - name: Install golangci-lint
          run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
  
        - name: Run golangci-lint
          run: |
            pushd ${{ matrix.directory }}
            golangci-lint run --timeout 5m
  
        - name: Run tests
          run: |
            go run cmd/shamir-coordinator/main.go
            pushd ${{ matrix.directory }}
            go test -race -vet=off ./...
